backend = "kmeans"
color_space = "lchmixed"
threshold = 15
filter = "softdark"
palette = "dark16"
saturation = 65

check_contrast = true

[templates]
# 'hypr' и 'waybar' — это уникальные ключи (названия) для шаблонов
hypr = { src = "hyprland.conf", dst = "~/.config/hypr/wallust-colors.conf" }
waybar = { src = "waybar.css", dst = "~/.config/waybar/wallust-colors.css" }
kitty = { src = "kitty.conf", dst = "~/.config/kitty/wallust-colors.conf" }
mango = { src = "mango.conf", dst = "~/.config/mango/wallust-colors.conf" }
dunst = { src = "dunstrc", dst = "~/.config/dunst/dunstrc" }
i3 = { src = "i3-colors", dst = "~/.config/i3/i3-colors" }
sway-colors = { src = "sway-colors", dst = "~/.config/sway/sway-colors" }
alacritty = { src = "alacritty.json", dst = "~/.config/alacritty/colors.toml" }
niri = { src = "niri.kdl", dst = "~/.config/niri/config.kdl" }

[entry]
command = "pkill -USR2 waybar" 
